on: [push]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    # - run: |
    #     curl -u "${{ secrets.USERNAME}}:${{secrets.TOKEN}}" \
    #       -H "Accept: application/vnd.github.everest-preview+json" \
    #       -H "Content-Type: application/json" \
    #       https://api.github.com/repos/defich/containers/actions/workflows/<workflow_id>.yaml/dispatches \
    #       --data '{"ref": "master"}'
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'defich',
            repo: 'containers',
            workflow_id: 'workflow_id',
            ref: 'main'
          })