name: dockerize-contextless

on:
  workflow_call:
    inputs:
     dockerfile:
      description: Docker file path
      type: string
      required: true
     tag:
      description: Docker tag
      type: string
      required: true
    secrets:
      username:
        description: Docker hub username
        required: true
      token:
        description: Docker hub token
        required: true

jobs:
  dockerize-contextless:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}
      - name: Build and publish
        run: | 
          set -Eeuo pipefail
          dockerfile="${{ inputs.dockerfile }}"
          tag="${{ inputs.tag }}"

          docker build -t "${tag}" - < "${dockerfile}"
          docker push "${tag}"

