name: dockerize-contextless

on:
  workflow_call:
    inputs:
     dockerfile: 
      type: string
      required: true
     tag:
      type: string
      required: true
    secrets:
      username: 
        required: true
      token:
        required: true

jobs:
  dockerize-contextless:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}
      - name: Build and publish
        run: | 
          set -Eeuo pipefail
          docker build -t ${{ inputs.tag }} - < ${{ inputs.dockerfile }}
          docker push ${{ inputs.tag }}

