name: dockerize-templated

on:
  workflow_call:
    inputs:
     contextdir:
       type: string
       required: false
     dockerfile: 
      type: string
      required: true
     tag:
      type: string
      required: true
    secrets:
      username: 
        required: true
      token:
        required: true

jobs:
  dockerize-templated:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}
      - name: Expand templates
        run: |
          container_hash=$(docker create docker.io/hairyhenderson/gomplate:stable)
          docker cp $container_hash:/gomplate /usr/local/bin/gomplate
          ./scripts/expand-template.sh "${{ inputs.contextdir }}"
      - name: Build and publish
        run: | 
          set -Eeuo pipefail
          build_dir="./build"
          contextdir="${build_dir}/${{ inputs.contextdir }}"
          dockerfile="${build_dir}/${{ inputs.dockerfile }}"
          tag="${{ inputs.tag }}"

          docker build -f "${dockerfile}" -t "${tag}" "${contextdir}" 
          # docker push "${tag}"

