name: dockerize-templated

on:
  workflow_call:
    inputs:
     contextdir:
      description: Docker context dir
      type: string
      required: false
     dockerfile: 
      description: Dockerfile path
      type: string
      required: true
     tag:
      description: Docker tag
      type: string
      required: true
    secrets:
      username: 
        description: Docker hub username
        required: true
      token:
        description: Docker hub token
        required: true

jobs:
  dockerize-templated:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.username }}
          password: ${{ secrets.token }}
      - name: Expand templates
        run: make expand-templates CONTEXT_DIR="${{ inputs.contextdir }}"
      - name: Build and publish
        run: | 
          set -Eeuo pipefail
          build_dir="./build"
          contextdir="${build_dir}/${{ inputs.contextdir }}"
          dockerfile="${build_dir}/${{ inputs.dockerfile }}"
          tag="${{ inputs.tag }}"

          docker build -f "${dockerfile}" -t "${tag}" "${contextdir}" 
          docker push "${tag}"

