name: mdbook

on:
  push:
    paths:
      - 'mdbook.dockerfile'

jobs:
  dockerize:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Login to Docker Hub
        uses: ./.github/workflows/dockerize-contextless.yaml
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          token: ${{ secrets.DOCKER_HUB_TOKEN }}
          dockerfile: mdbook.dockerfile
          tag: mdbook:latest

