name: mdbook

on:
  push:
    paths:
      - 'mdbook.dockerfile'
  
  workflow_dispatch:

jobs:
  dockerize:
      uses: ./.github/workflows/dockerize-contextless.yaml
      with:
        dockerfile: mdbook.dockerfile
        tag: defi/mdbook:latest
      secrets:
        username: ${{ secrets.DOCKER_HUB_USER }}
        token: ${{ secrets.DOCKER_HUB_TOKEN }}

