name: mdbook

on:
  push:
    paths:
      - 'mdbook.dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and publish
        run: | 
          set -Eeuo pipefail
          docker build -t mdbook:latest - < mdbook.dockerfile
          docker push mdbook:latest
