name: mdbook

on:
  push:
    paths:
      - 'mdbook.dockerfile'
  schedule:
    # Runs daily
    - cron:  '0 1 * * *'
  
  workflow_dispatch:

jobs:
  dockerize:
      uses: ./.github/workflows/dockerize.yaml
      with:
        dockerfile: mdbook.dockerfile
        tag: defi/mdbook:latest
      secrets:
        username: ${{ secrets.DOCKER_HUB_USER }}
        token: ${{ secrets.DOCKER_HUB_TOKEN }}
