name: mdbook

on:
  push:
    paths:
      - 'mdbook.dockerfile'

jobs:
  dockerize:
      uses: ./.github/workflows/dockerize-contextless.yaml
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        token: ${{ secrets.DOCKER_HUB_TOKEN }}
        dockerfile: mdbook.dockerfile
        tag: mdbook:latest

